version: "3.9"

services:
  product-api-gateway:
    build:
      dockerfile: ../Dockerfile.nodejs.prod
    image: thucnguyen95/product-api-gateway:latest
    command: sh /home/node/app/start.sh

  product-search-ingestion:
    build:
      dockerfile: ../Dockerfile.nodejs.prod
    image: thucnguyen95/product-search-ingestion:latest
    command: sh /home/node/app/start.sh

  product-search-service:
    build:
      dockerfile: ../Dockerfile.nodejs.prod
    image: thucnguyen95/product-search-service:latest
    command: sh /home/node/app/start.sh
