apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-loadbalancer
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
        - containerPort: 8080